
const ADDCONTACT = "ADD_CONTACT";
const DELETECONTACT = "DELETE_CONTACT";
const FILTERCONTACT = "FILER_CONTACT";
const UPDATECONTACT = "UPDATE_CONTACT";
const CHANGEALERT = "CHANGE_ALERT";
const RESETSELECTED = "RESET_SELECTED";
const ADDTOSELECTED = "ADD_TO_SELECTED";
const CHANGECONTACT = "CHANGE_CONTACT";
const CHEKUPDATEDITEMS="CHECK_UPDATED_ITEMS";
const GETCONTACTS = "GET_CONTACTS";

export {
  ADDCONTACT,
  DELETECONTACT,
  FILTERCONTACT,
  UPDATECONTACT,
  CHANGEALERT,
  RESETSELECTED,
  ADDTOSELECTED,
  CHANGECONTACT,
  CHEKUPDATEDITEMS,
  GETCONTACTS
};